test:
	xcodebuild \
		-sdk iphonesimulator \
		-workspace ___PROJECTNAME___.xcworkspace \
		-scheme ___PROJECTNAME___Tests \
		-configuration Debug \
		clean build \
		ONLY_ACTIVE_ARCH=NO \
		TEST_AFTER_BUILD=YES \
